# Generated by Django 4.0.1 on 2022-05-10 10:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercises',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('start_date', models.DateField(auto_now_add=True)),
                ('dedline', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('accepted', 'Accepted'), ('completed', 'Completed'), ('cancel', 'Cancel')], default='active', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=200)),
                ('birth_date', models.DateField()),
                ('name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Work_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True)),
                ('name_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worker.worker')),
                ('worker_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worker.exercises')),
            ],
        ),
    ]
